### ISSUE TITLE
Robomimic replay waypoint issue

### ISSUE THREAD

**Issue by palashag12** [lucys0/awe#6]
Hi, when trying to run the replay waypoint command I run into this issue

**Comment by palashag12** [comment]
Traceback (most recent call last):
  File "/home/pa1077/anaconda3/envs/awe_venv/lib/python3.9/site-packages/imageio_ffmpeg/_io.py", line 627, in write_frames
    p.stdin.write(bb)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pa1077/awe/example/robomimic_waypoint_replay.py", line 407, in <module>
    main(args)
  File "/home/pa1077/awe/example/robomimic_waypoint_replay.py", line 178, in main
    pred_states_list, _, traj_err = reconstruct_waypoint_trajectory(
  File "/home/pa1077/awe/waypoint_extraction/traj_reconstruction.py", line 185, in reconstruct_waypoint_trajectory
    video_writer.append_data(frame)
  File "/home/pa1077/anaconda3/envs/awe_venv/lib/python3.9/site-packages/imageio/core/format.py", line 590, in append_data
    return self._append_data(im, total_meta)
  File "/home/pa1077/anaconda3/envs/awe_venv/lib/python3.9/site-packages/imageio/plugins/ffmpeg.py", line 600, in _append_data
    self._write_gen.send(im)
  File "/home/pa1077/anaconda3/envs/awe_venv/lib/python3.9/site-packages/imageio_ffmpeg/_io.py", line 634, in write_frames
    raise IOError(msg)
OSError: [Errno 32] Broken pipe

I'm not sure whats going on any I belive I installed the packages correctly. I have no problem running any other files. I would greatly aprreciate some feedback regarding this.
Thanks!

**Comment by chad-yao** [comment]
It seems like `frame` is None or not an image array.
